/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.space.register.GuiView.JavaApplication1.src.guiview.panel;

import com.space.register.GuiViewController.FollowAndDiggController;

/**
 *
 * @author Administrator
 */
public class FollowPanel extends javax.swing.JPanel {

    /**
     * Creates new form FollowPanel
     */
    public FollowPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        followButton = new javax.swing.JButton();
        diggButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logText = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        userAccount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        videoId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dyid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modify = new javax.swing.JButton();
        appLog = new javax.swing.JButton();

        followButton.setText("关注");
        followButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followButtonActionPerformed(evt);
            }
        });

        diggButton.setText("点赞");
        diggButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diggButtonActionPerformed(evt);
            }
        });

        logText.setColumns(20);
        logText.setLineWrap(true);
        logText.setRows(5);
        jScrollPane1.setViewportView(logText);

        jLabel1.setText("输出");

        userAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userAccountActionPerformed(evt);
            }
        });

        jLabel2.setText("账号信息：");

        videoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoIdActionPerformed(evt);
            }
        });

        jLabel3.setText("视频信息：");

        dyid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dyidActionPerformed(evt);
            }
        });

        jLabel4.setText("选择id：");

        modify.setText("修改账号信息");
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        appLog.setText("app_log");
        appLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dyid, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(appLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(videoId)
                                .addGap(18, 18, 18)
                                .addComponent(diggButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(userAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(followButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(followButton)
                    .addComponent(userAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(dyid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(modify))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(diggButton)
                        .addComponent(videoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(appLog))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userAccountActionPerformed

    private void followButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followButtonActionPerformed
        // TODO add your handling code here:
        String userid = userAccount.getText();
        if (!userid.equals("") && userid!=null && dyid.getText()!=null) {
            FollowAndDiggController.follow(dyid.getText(),userid, logText);
        } else {
            logText.append("用户id不能为空\n");
        }
    }//GEN-LAST:event_followButtonActionPerformed

    private void diggButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diggButtonActionPerformed
        String userid = dyid.getText();
        if (!videoId.getText().equals("") && userid!=null) {
            FollowAndDiggController.digg(userid, videoId.getText(), logText);
        } else {
            logText.append("视频id不能为空\n");
        }
    }//GEN-LAST:event_diggButtonActionPerformed

    private void videoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_videoIdActionPerformed

    private void dyidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dyidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dyidActionPerformed

    /**
     * 修改资料监听
     * @param evt
     */
    private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
        String userid = dyid.getText();
        if (!userid.equals("") && userid!=null) {
            FollowAndDiggController.modify(dyid.getText(), null, logText );
        } else {
            logText.append("视频id不能为空\n");
        }
    }//GEN-LAST:event_modifyActionPerformed

    /**
     * applog监听
     * @param evt
     */
    private void appLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appLogActionPerformed
        // TODO add your handling code here:
        String userid = dyid.getText();
        if (!userid.equals("")&& userid!=null) {
            FollowAndDiggController.app_log(userid, logText);
        }
    }//GEN-LAST:event_appLogActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appLog;
    private javax.swing.JButton diggButton;
    private javax.swing.JTextField dyid;
    private javax.swing.JButton followButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logText;
    private javax.swing.JButton modify;
    private javax.swing.JTextField userAccount;
    private javax.swing.JTextField videoId;
    // End of variables declaration//GEN-END:variables
}
